language: ruby

rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head

before_install: "gem install bundler && gem install rspec"

cache: bundler

script: bundle exec rspec

bundler_args: --without development --jobs=3 --retry=3 --path=../vendor/bundle